Add files via upload
OpenAstronomy/openastronomy.github.io pull request #275
Opened 2021-02-19 16:45 UTC by barrettp

Adding NOVAS project

2021-02-19 17:34 UTC, bsipocz commented
This is a JuliaAstro project, isn't it? Then it should go in a juliaastro directory.

2021-02-19 17:46 UTC, barrettp commented
Yes, I suppose so. Then how do I get it included in the GSOC projects 2021
directory?  I'm a novice at this.


On Fri, Feb 19, 2021 at 12:34 PM Brigitta Sipőcz <notifications@github.com>
wrote:

> This is a JuliaAstro project, isn't it? Then it should go in a juliaastro
> directory.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenAstronomy/openastronomy.github.io/pull/275#issuecomment-782224453>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEPMRV25KOEI24NNATNR7LS72OLDANCNFSM4X4VWGDQ>
> .
>

2021-02-19 18:14 UTC, bsipocz commented
It's basically the same you did, just rename the novas directory to juliaastro.

2021-02-19 18:47 UTC, dpshelio requested changes
Some other small changes to make the build happy.

2021-02-19 18:47 UTC, dpshelio commented on _projects/2021/novas/NOVAS.md
> +Astrometry Software (NOVAS) library and vectorize it to improve performance.
```suggestion
desc: Implement a Julia vectorized version of the NOVAS library
```

2021-02-19 18:47 UTC, dpshelio commented on _projects/2021/novas/NOVAS.md
> +This is an awesome project idea for suborg.
```suggestion
Implement a Julia version of the U.S. Naval Observatory Vector Astrometry 
Software (NOVAS) library and vectorize it to improve performance.
```

2021-03-09 20:13 UTC, bsipocz commented
@giordano - would you or someone else be a second mentor for this project? If yes, please add the github handle, and we can merge the PR.

2021-03-09 20:15 UTC, giordano commented on _projects/2021/juliaastro/NOVAS.md
> + - pebarrett
Yes, I'm happy to be the second mentor
```suggestion
 - pebarrett
 - giordano
```

2021-03-09 20:32 UTC, bsipocz approved these changes

2021-03-09 20:33 UTC, bsipocz approved these changes

2021-03-09 20:33 UTC, merged