Astroquery project addition
OpenAstronomy/openastronomy.github.io pull request #277
Opened 2021-03-02 05:59 UTC by aaryapatil

GSoC project to add new services to astroquery.

2021-03-03 13:38 UTC, dpshelio requested changes
Nice to see astroquery proposing projects this year!

2021-03-03 13:38 UTC, dpshelio commented on _projects/2021/astropy/astroquery.md
> +
There is only one evaluation this year, this should be moved into the final block.

2021-03-03 13:38 UTC, dpshelio commented on _projects/2021/astropy/astroquery.md
> +
It would be good to add links to any service mentioned in the description that the students will have to implement.

2021-03-03 17:32 UTC, bsipocz requested changes
This needs discussion with the astroquery maintainers to align with roadmap and priorities

2021-03-09 01:31 UTC, aaryapatil commented
We decided to not do this project for GSoC after talking to the maintainers.

2021-03-09 01:31 UTC, closed without merging